name: Cron trigger

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  trigger:
    uses: ./.github/workflows/test.yaml
    with:
      test_type: Daily
      artifact_url: 'https://ghartifactscac001.blob.core.windows.net/builds/downstream_pirs-automation.zip'
